### ISSUE TITLE
丢刀以及弓箭问题

### ISSUE THREAD

**Issue by Demonst183** [Skillw/AttributeSystem#4]
服务端核心Paper1.19.4最终构建；插件版本AttributeSystem-2.0.0-gamma-17.jar；附属FightSystem-1.0.0-gamma-13.jar
进行攻击时在原版极限距离下无法击中目标，有原版命中反馈，将攻击距离提高能降低丢刀概率，攻击距离超出原版距离时不会丢刀，
只有攻击的前几次会丢失，只要命中之后接下来的伤害不会丢失
使用弓时，箭矢无法接触生物或直接穿过生物，修改攻击距离后可以使用箭矢命中生物但弓本身可以在范围内左键攻击生物

没有在控制台中发现任何和上述问题相关的插件的任意报错

**Comment by Glomzzz** [comment]
新版已修复，感谢
